Service de Auditoria
lauraizabel/condominio-poo pull request #33
Opened 2021-12-21 00:47 UTC by monxqueen

# **Vejam se falta algo por favorrrr**
Vê aí namoral

2021-12-22 17:54 UTC, Wili-Souza requested changes
Esse service de auditoria que tu criasse só tem as funcionalidades padrão. Toda modificação nas tabelas deveriam ser registradas no BD através de auditoria, era dessa implementação que a gente tava falando

2021-12-28 01:26 UTC, lauraizabel commented
Adicionei o restante das coisas que eram necessárias pra Auditoria funcionar corretamente, agora só tem um problema que é a repetição de blocos de códigos nos services, mas isso eu considero mais uma melhoria futura, considerando que agora tá funcionando direitinho

2021-12-28 15:16 UTC, Gquaresma approved these changes

2021-12-28 16:25 UTC, Wili-Souza approved these changes

2021-12-29 00:03 UTC, merged